# Generated by Django 3.1.4 on 2021-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('last_date', models.DateField()),
                ('last_time', models.TimeField()),
            ],
        ),
    ]
