# Generated by Django 3.1.4 on 2021-01-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='example@gamil.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='pswd',
            field=models.CharField(default=12345678, max_length=20),
            preserve_default=False,
        ),
    ]
