# Generated by Django 3.1.4 on 2021-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210109_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.FileField(default='empty file', upload_to=''),
            preserve_default=False,
        ),
    ]
