# Generated by Django 3.1.4 on 2021-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='no_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
