# Generated by Django 3.1.4 on 2021-01-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0002_participate_no_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participate',
            old_name='no_people',
            new_name='no_of_people',
        ),
    ]
